# Generated by Django 4.2.7 on 2025-07-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("upgrade", "Upgrade"),
                            ("renewal", "Renewal"),
                            ("lifetime", "Lifetime"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subscription_type", models.CharField(blank=True, max_length=20)),
                (
                    "subscription_duration_days",
                    models.IntegerField(blank=True, null=True),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("gateway", models.CharField(blank=True, max_length=50)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payment_rec_user_id_987843_idx"
                    ),
                    models.Index(
                        fields=["payment_type", "created_at"],
                        name="payment_rec_payment_4a6e05_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="payment_rec_status_91f756_idx",
                    ),
                ],
            },
        ),
    ]
