# Generated by Django 4.2.7 on 2025-08-06 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, help_text="Company name", max_length=255, null=True
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        help_text="Owner/Your name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State/Province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City", max_length=100, null=True
                    ),
                ),
                (
                    "year_started",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year business was started", null=True
                    ),
                ),
                (
                    "trucks_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of trucks in operation", null=True
                    ),
                ),
                (
                    "monthly_revenue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-5k", "$0 - $5,000"),
                            ("5k-10k", "$5,000 - $10,000"),
                            ("10k-25k", "$10,000 - $25,000"),
                            ("25k-50k", "$25,000 - $50,000"),
                            ("50k-100k", "$50,000 - $100,000"),
                            ("100k+", "$100,000+"),
                        ],
                        help_text="Monthly revenue range",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "gross_profit_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gross profit margin estimate (percentage)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "main_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Main services offered (checklist)",
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per_cubic_yard", "Per Cubic Yard"),
                            ("per_pound", "Per Pound"),
                            ("flat_rate", "Flat Rate"),
                            ("hourly", "Hourly"),
                            ("other", "Other"),
                        ],
                        help_text="Pricing model used",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "software_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Software tools used (CRM, booking, GPS, etc.)",
                    ),
                ),
                (
                    "current_challenges",
                    models.TextField(
                        blank=True,
                        help_text="Top current challenges (free text)",
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the client info form has been completed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Info",
                "verbose_name_plural": "Client Info",
                "db_table": "client_info",
                "ordering": ["-created_at"],
            },
        ),
    ]
