# Generated by Django 4.2.7 on 2025-08-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_clientinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinfo",
            name="monthly_revenue",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-250k", "$0 - $250,000"),
                    ("250k-500k", "$250,000 - $500,000"),
                    ("500k-1m", "$500,000 - $1,000,000"),
                    ("1m-2m", "$1,000,000 - $2,000,000"),
                    ("2m-4m", "$2,000,000 - $4,000,000"),
                    ("4m+", "$4,000,000+"),
                ],
                help_text="Monthly revenue range",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientinfo",
            name="pricing_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("by_weight", "By weight"),
                    ("by_volume", "By volume"),
                    ("by_hour", "By the hour"),
                    ("other", "Other"),
                ],
                help_text="Pricing model used",
                max_length=20,
                null=True,
            ),
        ),
    ]
