# Generated by Django 4.2.7 on 2025-07-02 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                ("file_extension", models.CharField(max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("bucket_name", models.CharField(max_length=100)),
                ("object_key", models.CharField(max_length=500)),
                ("minio_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("upload_progress", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_download", models.BooleanField(default=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_comment", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="files.file",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files_shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_shares",
            },
        ),
        migrations.CreateModel(
            name="FileComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="files.file",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="files.filecomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_files",
                through="files.FileShare",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("object_key", models.CharField(max_length=500)),
                ("change_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="files.file",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_versions",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["file", "version_number"],
                        name="file_versio_file_id_9af039_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="file_versio_created_a05ee7_idx"
                    ),
                ],
                "unique_together": {("file", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["shared_by", "created_at"],
                name="file_shares_shared__63a11b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["shared_with", "created_at"],
                name="file_shares_shared__dc9b7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileshare",
            index=models.Index(
                fields=["expires_at"], name="file_shares_expires_1bc2a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fileshare",
            unique_together={("file", "shared_with")},
        ),
        migrations.AddIndex(
            model_name="filecomment",
            index=models.Index(
                fields=["file", "created_at"], name="file_commen_file_id_974bd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filecomment",
            index=models.Index(
                fields=["user", "created_at"], name="file_commen_user_id_8d32ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["user", "status"], name="files_user_id_bf2cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["category", "created_at"], name="files_categor_a0a457_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["file_type"], name="files_file_ty_08ab7b_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["is_public", "is_shared"], name="files_is_publ_8979d4_idx"
            ),
        ),
    ]
