# Generated by Django 4.2.7 on 2025-08-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="bucket_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
