# Generated by Django 4.2.7 on 2025-07-02 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Conversation title (auto-generated from first message)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Whether conversation is archived"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Whether conversation is pinned"
                    ),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of messages in conversation"
                    ),
                ),
                (
                    "total_tokens_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Total tokens used in this conversation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "chat_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=100)),
                ("description", models.TextField(help_text="Template description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("business", "Business"),
                            ("technical", "Technical"),
                            ("creative", "Creative"),
                            ("educational", "Educational"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(help_text="Template prompt text")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether template is available to all users",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times template has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Template",
                "verbose_name_plural": "Chat Templates",
                "db_table": "chat_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        help_text="Type of message (user, assistant, system)",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        help_text="Message processing status",
                        max_length=10,
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of tokens used for this message",
                        null=True,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="AI model used to generate response",
                        max_length=100,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="User feedback on message helpfulness",
                        null=True,
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(blank=True, help_text="User feedback comment"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_conver_user_id_9d8b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "is_archived"], name="chat_conver_user_id_d5e8c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "is_pinned"], name="chat_conver_user_id_c9072a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chattemplate",
            index=models.Index(
                fields=["category", "is_public"], name="chat_templa_categor_0b2fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chattemplate",
            index=models.Index(
                fields=["-usage_count"], name="chat_templa_usage_c_23f0e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_0a903c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_messag_user_id_790302_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["message_type", "status"], name="chat_messag_message_300ff1_idx"
            ),
        ),
    ]
