# Generated by Django 4.2.7 on 2025-08-04 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Folder name", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional folder description"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Folder color in hex format",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
                "db_table": "chat_folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder containing this conversation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="chat.folder",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "folder"], name="chat_conver_user_id_faae40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["folder", "-updated_at"], name="chat_conver_folder__531400_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["user", "name"], name="chat_folder_user_id_74cc6d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("user", "name")},
        ),
    ]
