# Generated by Django 4.2.7 on 2025-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_folder_conversation_chat_conver_user_id_faae40_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of source documents used for this response",
            ),
        ),
    ]
